name: Run Cucumber selenium tests

on:
  push:
    branches: [ "*" ]

  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser name'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox
          - safari
          - edge
          - ie
          - unit


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Install maven
      run: mvn package -Dmaven.test.skip

    - name: Run test
      run: mvn test -Dtesting.dtd.http=true
