name: Run Cucumber selenium tests

on:
  push:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

#    services:
#      selenium:
#        image: selenium/standalone-chrome:latest
#        ports:
#          - 4444:4444
#        options: --shm-size="2g"

    steps:
    - uses: actions/checkout@v3
#
#    - name: Get IP Address
#      run: ifconfig eth0 | grep 'inet [0-9\.]* ' -o | sed 's/[^0-9\.]//g'
#      id: ip_addr

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Install maven
      run: mvn package -Dmaven.test.skip

    - name: Run test
      run: mvn test -Dtesting.dtd.http=true
